---
title: "Data Preperation"
output: html_document
date: "2024-06-14"
---

#Importing the necessary libraries
```{r}
library(stringr)
library(clustertend)
library(NbClust)
library(factoextra)
library(ClusterR)
library(fpc)
library(clusterSim)
library(psych)
library(FactoMineR)
library(clustMixType)
library(dplyr)
library(tidyr)
```

# Loading the data file from Wave 2 interviews to calculate the BMI
```{r}
load("34921-0001-Data.rda")

da34921.0001 <- da34921.0001 %>%
  mutate(BMI = ((WEIGHT)/(HEIGHT*HEIGHT) * 703),
         OBESITY = case_when(
           ((WEIGHT)/(HEIGHT*HEIGHT) * 703) >= 30.000 ~ 1,
           ((WEIGHT)/(HEIGHT*HEIGHT) * 703) < 30.000 ~ 0
         )) 

obesity <- da34921.0001 %>% select(ID, OBESITY, BMI)
head(obesity)

```


# Loading and Processing the Independent Social Network Variables to calculate Bridge from WAVE 1.
```{r}

load("20541-0001-Data.rda")
load("20541-0004-Data.rda")


da20541.0001 <- da20541.0001 %>%
  select (ID, HEARN_RECODE, GENDER, AGE, RACE_RECODE, ETHGRP, COMBUILD, DEGREE_RECODE, HISPANIC, MARITLST,JOBSTAT_1, PHYSHLTH, MNTLHLTH, ATNDSERV )
```

```{r}

da20541.0001 <- da20541.0001 %>%
  mutate(DEGREE_RECODE = if_else(DEGREE_RECODE == "(-2) don't know", NA, DEGREE_RECODE),
         HEARN_RECODE = if_else(HEARN_RECODE == "(-2) don't know", NA, HEARN_RECODE),
         RACE_RECODE = if_else(RACE_RECODE == "(-2) don't know", NA, RACE_RECODE))
```

```{r}
head(da20541.0001)
nrow(da20541.0001)
```



```{r}
da20541.0004 <- da20541.0004 %>%
  group_by(ID) %>%
  filter(n() > 2) %>%
  ungroup()
```

```{r}
da20541.0004 <- da20541.0004 %>%
  pivot_longer(
    cols = starts_with("TALKFREQ"),
    names_to = "TALKFREQ",
    values_to = "FREQ"
  )

da20541.0004 <- da20541.0004 %>%
  group_by(ID) %>%
  summarize(
    BRIDGE = if_else(any(FREQ == '(0) have never spoken to each other', na.rm = TRUE), 1, 0),
    HEALTHDISCUSSIONS = if_else(any(HEALTHTALK == '(3) very likely', na.rm = TRUE), 1, 0),
    LIVEALONE = if_else(any(LIVEWITH == '(1) yes -- lives in the same household', na.rm = TRUE), 0,1))
  
head(da20541.0004)
```

```{r}
nrow(da20541.0004)
```


```{r}
modeldata <- da20541.0001 %>%
  left_join(da20541.0004, by = "ID")

modeldata <- modeldata %>%
  left_join(obesity, by = "ID")

modeldata<- na.omit(modeldata)
modeldata <- modeldata %>% select(-ID)

modeldata$BRIDGE <- as.factor(modeldata$BRIDGE)
modeldata$HEALTHDISCUSSIONS <- as.factor(modeldata$HEALTHDISCUSSIONS)
modeldata$LIVEALONE <- as.factor(modeldata$LIVEALONE)
modeldata$OBESITY <- as.factor(modeldata$OBESITY)
head(modeldata)
```

```{r}
write.csv(modeldata, "modeldata.csv", row.names = FALSE)
```